/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoBD;


/**
 *
 * @author Railda
 */
public class PrincipalTela extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
           
    /**
     * Creates new form PrincipalTela
     */
    public PrincipalTela() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpainel = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        relatorio = new javax.swing.JButton();
        venda = new javax.swing.JButton();
        cadastroveiculo = new javax.swing.JButton();
        cadastrocidade = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        imagempainel = new javax.swing.JLabel();
        nomegerenciamento = new javax.swing.JLabel();
        imagemtelaprmcipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastro = new javax.swing.JMenu();
        submenucliente = new javax.swing.JMenuItem();
        submenuveiculo = new javax.swing.JMenuItem();
        submenuusuario = new javax.swing.JMenuItem();
        submenupassagem = new javax.swing.JMenuItem();
        menurelatorio = new javax.swing.JMenu();
        submenurelatorio = new javax.swing.JMenuItem();
        menuferramenta = new javax.swing.JMenu();
        submenubemvindo = new javax.swing.JMenuItem();
        submenuvenda = new javax.swing.JMenuItem();
        menusair = new javax.swing.JMenu();
        submenusair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jpainel.setTitle("Bem-Vindo");
        jpainel.setVisible(true);
        jpainel.getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisarr.jpg"))); // NOI18N
        relatorio.setToolTipText("Relatório Geral ");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        jPanel3.add(relatorio);
        relatorio.setBounds(180, 210, 180, 190);

        venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/venda.png"))); // NOI18N
        venda.setToolTipText("Venda Da Passagem");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        jPanel3.add(venda);
        venda.setBounds(360, 0, 180, 190);

        cadastroveiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cadastro veiculo.jpg"))); // NOI18N
        cadastroveiculo.setToolTipText("Cadastra Um Veículo No Sistema");
        cadastroveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroveiculoActionPerformed(evt);
            }
        });
        jPanel3.add(cadastroveiculo);
        cadastroveiculo.setBounds(180, 0, 180, 190);

        cadastrocidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mapa.png"))); // NOI18N
        cadastrocidade.setToolTipText("Cadastra Uma Cidade No Sistema");
        cadastrocidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrocidadeActionPerformed(evt);
            }
        });
        jPanel3.add(cadastrocidade);
        cadastrocidade.setBounds(0, 210, 180, 190);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fechar (Copy).png"))); // NOI18N
        jButton7.setToolTipText("Fechar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(1230, 10, 120, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/novo_cadastro-usuario.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 0, 180, 190);

        imagempainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/jframe.png"))); // NOI18N
        jPanel3.add(imagempainel);
        imagempainel.setBounds(0, 0, 1380, 470);

        jpainel.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 50, 1370, 400);

        nomegerenciamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomegerenciamento.setText("Sistema De Gerenciamento ");
        jpainel.getContentPane().add(nomegerenciamento);
        nomegerenciamento.setBounds(580, 0, 250, 19);

        getContentPane().add(jpainel);
        jpainel.setBounds(0, 190, 1360, 500);

        imagemtelaprmcipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(imagemtelaprmcipal);
        imagemtelaprmcipal.setBounds(0, 0, 1370, 770);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(920, 70, 10, 10);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(600, 32769));
        jMenuBar1.setName(""); // NOI18N

        menucadastro.setText("Cadastro");
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });

        submenucliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        submenucliente.setText("Cliente");
        submenucliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuclienteActionPerformed(evt);
            }
        });
        menucadastro.add(submenucliente);

        submenuveiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        submenuveiculo.setText("Veículo");
        submenuveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuveiculoActionPerformed(evt);
            }
        });
        menucadastro.add(submenuveiculo);

        submenuusuario.setText("Usuario");
        submenuusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuusuarioActionPerformed(evt);
            }
        });
        menucadastro.add(submenuusuario);

        submenupassagem.setText("Venda");
        submenupassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenupassagemActionPerformed(evt);
            }
        });
        menucadastro.add(submenupassagem);

        jMenuBar1.add(menucadastro);

        menurelatorio.setText("Relatorio");

        submenurelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        submenurelatorio.setText("Rlatorio Geral");
        submenurelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenurelatorioActionPerformed(evt);
            }
        });
        menurelatorio.add(submenurelatorio);

        jMenuBar1.add(menurelatorio);

        menuferramenta.setText("Ferramentas");

        submenubemvindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        submenubemvindo.setText("Tela-Bem-Vindo");
        submenubemvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenubemvindoActionPerformed(evt);
            }
        });
        menuferramenta.add(submenubemvindo);

        submenuvenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        submenuvenda.setText("Venda");
        menuferramenta.add(submenuvenda);

        jMenuBar1.add(menuferramenta);

        menusair.setText("Sair");
        menusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusairActionPerformed(evt);
            }
        });

        submenusair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        submenusair.setText("Sair");
        submenusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenusairActionPerformed(evt);
            }
        });
        menusair.add(submenusair);

        jMenuBar1.add(menusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1387, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menusairActionPerformed

    private void submenusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenusairActionPerformed
        

        System.exit(0);
                
        
        // TODO add your handling code here:
    }//GEN-LAST:event_submenusairActionPerformed

    private void submenubemvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenubemvindoActionPerformed
        PrincipalTela tela = new PrincipalTela();
        tela.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_submenubemvindoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jpainel.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed

        VendaPassagem tela = new VendaPassagem();
        tela.setVisible(true);
      


        // TODO add your handling code here:
    }//GEN-LAST:event_vendaActionPerformed

    private void submenuveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuveiculoActionPerformed
 Veiculo tela = new Veiculo();
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_submenuveiculoActionPerformed

    private void cadastroveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroveiculoActionPerformed

Veiculo tela = new Veiculo();
        tela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroveiculoActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
Relatorio tela = new Relatorio();
        tela.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_relatorioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Usuario tela = new Usuario();
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submenuusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuusuarioActionPerformed
Usuario tela = new Usuario();
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_submenuusuarioActionPerformed

    private void submenupassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenupassagemActionPerformed
VendaPassagem tela = new VendaPassagem();
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_submenupassagemActionPerformed

    private void cadastrocidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrocidadeActionPerformed
        Cidade tela = new Cidade();
        tela.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrocidadeActionPerformed

    private void submenuclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuclienteActionPerformed
            Cidade tela = new Cidade();
        tela.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_submenuclienteActionPerformed

    private void submenurelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenurelatorioActionPerformed
            Relatorio tela = new Relatorio();
        tela.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_submenurelatorioActionPerformed

    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrocidade;
    private javax.swing.JButton cadastroveiculo;
    private javax.swing.JLabel imagempainel;
    private javax.swing.JLabel imagemtelaprmcipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JInternalFrame jpainel;
    private javax.swing.JMenu menucadastro;
    private javax.swing.JMenu menuferramenta;
    private javax.swing.JMenu menurelatorio;
    private javax.swing.JMenu menusair;
    private javax.swing.JLabel nomegerenciamento;
    private javax.swing.JButton relatorio;
    private javax.swing.JMenuItem submenubemvindo;
    private javax.swing.JMenuItem submenucliente;
    private javax.swing.JMenuItem submenupassagem;
    private javax.swing.JMenuItem submenurelatorio;
    private javax.swing.JMenuItem submenusair;
    private javax.swing.JMenuItem submenuusuario;
    private javax.swing.JMenuItem submenuveiculo;
    private javax.swing.JMenuItem submenuvenda;
    private javax.swing.JButton venda;
    // End of variables declaration//GEN-END:variables

    private void Connection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
