/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoBD;
import controle_dao.VeiculoDAO;
import static java.awt.SystemColor.control;
import javax.swing.table.DefaultTableModel;
import modelo_beans.VeiculoBeans;

/**
 *
 * @author Railda
 */
public class Veiculo extends javax.swing.JFrame {

     VeiculoBeans vei = new VeiculoBeans();
    VeiculoDAO contv = new VeiculoDAO();
    ConexaoBD conex = new ConexaoBD();

    /**
     * Creates new form CadastroVeiculo
     */
    public Veiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numerov = new javax.swing.JLabel();
        placav = new javax.swing.JLabel();
        modelov = new javax.swing.JLabel();
        datav = new javax.swing.JLabel();
        poltronav = new javax.swing.JLabel();
        jbbotaocadastrav = new javax.swing.JButton();
        jbbotaolimpav = new javax.swing.JButton();
        jtcampoqpoltrona = new javax.swing.JTextField();
        jtcamponumero = new javax.swing.JTextField();
        jtcampoplaca = new javax.swing.JTextField();
        jtcampomodelo = new javax.swing.JTextField();
        nomeconsultav = new javax.swing.JLabel();
        pesquisav = new javax.swing.JLabel();
        jtcampopesquisav = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbbotao_excluir_v = new javax.swing.JButton();
        jbbotaookv = new javax.swing.JButton();
        nomemotoritaveiculo = new javax.swing.JLabel();
        jtcampomotoristaveiculo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campodadta = new javax.swing.JFormattedTextField();
        nomeveiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        numerov.setText("Numero:");
        jPanel1.add(numerov);
        numerov.setBounds(41, 40, 50, 20);

        placav.setText("Placa:");
        jPanel1.add(placav);
        placav.setBounds(41, 80, 50, 20);

        modelov.setText("Modelo:");
        jPanel1.add(modelov);
        modelov.setBounds(41, 120, 50, 20);

        datav.setText("Data Da Compra:");
        jPanel1.add(datav);
        datav.setBounds(280, 40, 100, 15);

        poltronav.setText("Quantidade Poltronas:");
        jPanel1.add(poltronav);
        poltronav.setBounds(280, 80, 130, 15);

        jbbotaocadastrav.setText("Cadastrar");
        jbbotaocadastrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbotaocadastravActionPerformed(evt);
            }
        });
        jPanel1.add(jbbotaocadastrav);
        jbbotaocadastrav.setBounds(310, 160, 100, 25);

        jbbotaolimpav.setText("Limpar");
        jbbotaolimpav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbotaolimpavActionPerformed(evt);
            }
        });
        jPanel1.add(jbbotaolimpav);
        jbbotaolimpav.setBounds(410, 160, 100, 25);

        jtcampoqpoltrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcampoqpoltronaActionPerformed(evt);
            }
        });
        jPanel1.add(jtcampoqpoltrona);
        jtcampoqpoltrona.setBounds(440, 80, 170, 19);

        jtcamponumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcamponumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jtcamponumero);
        jtcamponumero.setBounds(110, 40, 120, 19);
        jPanel1.add(jtcampoplaca);
        jtcampoplaca.setBounds(110, 80, 120, 19);
        jPanel1.add(jtcampomodelo);
        jtcampomodelo.setBounds(110, 120, 120, 19);

        nomeconsultav.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        nomeconsultav.setText("Consultar Veículo");
        jPanel1.add(nomeconsultav);
        nomeconsultav.setBounds(240, 210, 170, 16);

        pesquisav.setText("Pesquisar:");
        jPanel1.add(pesquisav);
        pesquisav.setBounds(60, 240, 70, 30);
        jPanel1.add(jtcampopesquisav);
        jtcampopesquisav.setBounds(130, 240, 300, 19);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Placa", "Modelo", "Nº Poltrona", "Data Compra", "Motorista"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 290, 570, 90);

        jbbotao_excluir_v.setText("Excluir");
        jbbotao_excluir_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbotao_excluir_vActionPerformed(evt);
            }
        });
        jPanel1.add(jbbotao_excluir_v);
        jbbotao_excluir_v.setBounds(290, 380, 66, 25);

        jbbotaookv.setText("Pesquisar");
        jPanel1.add(jbbotaookv);
        jbbotaookv.setBounds(440, 240, 90, 25);

        nomemotoritaveiculo.setText("Motorista:");
        jPanel1.add(nomemotoritaveiculo);
        nomemotoritaveiculo.setBounds(280, 120, 47, 15);

        jtcampomotoristaveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcampomotoristaveiculoActionPerformed(evt);
            }
        });
        jPanel1.add(jtcampomotoristaveiculo);
        jtcampomotoristaveiculo.setBounds(360, 120, 250, 19);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 160, 100, 25);
        jPanel1.add(campodadta);
        campodadta.setBounds(440, 40, 170, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 640, 420);

        nomeveiculo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        nomeveiculo.setText("Castro De Veículos");
        getContentPane().add(nomeveiculo);
        nomeveiculo.setBounds(280, 10, 149, 20);

        setSize(new java.awt.Dimension(752, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtcamponumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcamponumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcamponumeroActionPerformed

    private void jtcampoqpoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcampoqpoltronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcampoqpoltronaActionPerformed

    private void jbbotaocadastravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbotaocadastravActionPerformed
         vei.setPlacaVeiculo(jtcampoplaca.getText());
         vei.setDatacompraVeiculo(campodadta.getText());
         vei.setModeloVeiculo(jtcampomodelo.getText());
         vei.setMotoristaVeiculo(jtcampomotoristaveiculo.getText());
         vei.setQtdpoltronaVeiculo(Integer.parseInt (jtcampoqpoltrona.getText()));
         
         
         
        contv.salvarveiculo(vei);

        
        DefaultTableModel tab = (DefaultTableModel)tabela.getModel();


   Object[] dados = { jtcamponumero.getText().trim(),
         jtcampoplaca.getText().trim(),
         jtcampomodelo.getText().trim(),
         campodadta.getText().trim(),
         jtcampoqpoltrona.getText().trim(),
         jtcampomotoristaveiculo.getText().trim()
       };
   tab.addRow(dados);
        
            

        // TODO add your handling code here:
    }//GEN-LAST:event_jbbotaocadastravActionPerformed

    private void jbbotaolimpavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbotaolimpavActionPerformed
           
    jtcamponumero.setText("");
        jtcampoplaca.setText("");
         jtcampomodelo.setText("");
         campodadta.setText("");
         jtcampoqpoltrona.setText("");
         jtcampomotoristaveiculo.setText("");
         
               
      
          // TODO add your handling code here:
    }//GEN-LAST:event_jbbotaolimpavActionPerformed

    private void jbbotao_excluir_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbotao_excluir_vActionPerformed
((DefaultTableModel)tabela.getModel()).removeRow(tabela.getSelectedRow());

        // TODO add your handling code here:
    }//GEN-LAST:event_jbbotao_excluir_vActionPerformed

    private void jtcampomotoristaveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcampomotoristaveiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcampomotoristaveiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Veiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campodadta;
    private javax.swing.JLabel datav;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbbotao_excluir_v;
    private javax.swing.JButton jbbotaocadastrav;
    private javax.swing.JButton jbbotaolimpav;
    private javax.swing.JButton jbbotaookv;
    private javax.swing.JTextField jtcampomodelo;
    private javax.swing.JTextField jtcampomotoristaveiculo;
    private javax.swing.JTextField jtcamponumero;
    private javax.swing.JTextField jtcampopesquisav;
    private javax.swing.JTextField jtcampoplaca;
    private javax.swing.JTextField jtcampoqpoltrona;
    private javax.swing.JLabel modelov;
    private javax.swing.JLabel nomeconsultav;
    private javax.swing.JLabel nomemotoritaveiculo;
    private javax.swing.JLabel nomeveiculo;
    private javax.swing.JLabel numerov;
    private javax.swing.JLabel pesquisav;
    private javax.swing.JLabel placav;
    private javax.swing.JLabel poltronav;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    




}